### ISSUE TITLE
[기능추가] 배팅 상한선 10000원으로 설정

### ISSUE THREAD

**Issue by 201402407** [jeongjinhwi/RC#10]
배팅 상한선 변경.
또한, server side에서도 체크하기.

**Comment by NamJinWoo** [comment]
제가합니다이것도!

**Comment by NamJinWoo** [comment]
TooMuchBetException 클래스를 exception폴더에 만들고
bet이 10000 보다 크면 exception이 되게 만들어봄

**Comment by NamJinWoo** [comment]
public void placeBet(long bet) {
        if(balance < bet) {
            throw new NotEnoughBalanceException();
        }
        if(bet > 10000){
            throw new TooMuchBetException();
        }
        balance -= bet;
        currentBet = bet;

        isPlaying = true;
    }

**Comment by NamJinWoo** [comment]
server side에서도 체크하기.
이게 무엇인지 알고난후 다시 확인하겠음
