### ISSUE TITLE
[기능추가] 이전 bet을 default bet으로 설정

### ISSUE THREAD

**Issue by NamJinWoo** [jeongjinhwi/RC#11]
게임이 끝난 후 이전에 betting한 금액을 다음 게임 default bet으로 설정한다.

**Comment by jeongjinhwi** [comment]
제가 할게염

**Comment by jeongjinhwi** [comment]
jquery hit부분에서 currentBet가 아닌 previousBet으로 #bet에 넣기
 //$('#bet').html(gameRoom.playerList[user.name0.currentBet);
        $('#bet').html(gameRoom.playerList[user.name].previousBet);
        $('#money').html(gameRoom.playerList[user.name].balance);

previousBet은
Player의 placeBet에서 현재 bet을 previousBet에 넣고 그 다음순서에 호출
