### ISSUE TITLE
[기능추가] 배팅금액보다 적은 돈을 가지고 있으면 올인

### ISSUE THREAD

**Issue by 201402407** [jeongjinhwi/RC#13]
만약 현재 내가 가진 돈이 기본 배팅금액보다 낮으면 자동으로 올인하도록 수정하기.

**Comment by jeongjinhwi** [comment]
제가 할게염

**Comment by jeongjinhwi** [comment]
public void placeBet(long bet) {
        if(balance < bet) {
            bet = balance;
        }
        balance -= bet;
        currentBet = bet;
        previousBet = bet;

        isPlaying = true;
    }
Player 에 placeBet 함수에서 balance가 bet보다 작으면 bet을 balance로 설정해서 올인한다.
